import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TouchDownConnectSwarm",
  description: "Generated by anonimas",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <meta
        name={"apple-itunes-app"}
        content={"app-clip-bundle-id=com.touchdownconnectswarm.app.clip"}
        app-id={"LANULV72W5"}
    />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
